-- ==========================================================================
-- Sales Performance Dashboard - Advanced SQL Queries — MySQL 8.0+
-- ==========================================================================

USE superstore;


-- A1. DENSE_RANK — Rank sub-categories by profit
-- Ties receive the same rank without gaps.
SELECT
    p.sub_category,
    ROUND(SUM(f.profit), 2) AS total_profit,
    DENSE_RANK() OVER (
        ORDER BY SUM(f.profit) DESC
    ) AS profit_dense_rank
FROM fact_orders f
JOIN dim_products p
    ON f.product_id = p.product_id
GROUP BY p.sub_category
ORDER BY profit_dense_rank;


-- A2. LEAD — Compare each month's revenue with the following month
WITH monthly AS (
    SELECT
        order_year,
        order_month,
        SUM(sales) AS monthly_sales
    FROM fact_orders
    GROUP BY order_year, order_month
)
SELECT
    order_year,
    order_month,
    ROUND(monthly_sales, 2) AS monthly_sales,
    ROUND(
        LEAD(monthly_sales) OVER (
            ORDER BY order_year, order_month
        ), 2
    ) AS next_month_sales,
    ROUND(
        LEAD(monthly_sales) OVER (
            ORDER BY order_year, order_month
        ) - monthly_sales,
        2
    ) AS change_to_next_month
FROM monthly
ORDER BY order_year, order_month;


-- A3. 3-Month Moving Average of Revenue
WITH monthly AS (
    SELECT
        order_year,
        order_month,
        SUM(sales) AS monthly_sales
    FROM fact_orders
    GROUP BY order_year, order_month
)
SELECT
    order_year,
    order_month,
    ROUND(monthly_sales, 2) AS monthly_sales,
    ROUND(
        AVG(monthly_sales) OVER (
            ORDER BY order_year, order_month
            ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
        ),
        2
    ) AS moving_avg_3mo
FROM monthly
ORDER BY order_year, order_month;


-- A4. Rolling 3-Month Revenue Total
WITH monthly AS (
    SELECT
        order_year,
        order_month,
        SUM(sales) AS monthly_sales
    FROM fact_orders
    GROUP BY order_year, order_month
)
SELECT
    order_year,
    order_month,
    ROUND(monthly_sales, 2) AS monthly_sales,
    ROUND(
        SUM(monthly_sales) OVER (
            ORDER BY order_year, order_month
            ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
        ),
        2
    ) AS rolling_3mo_revenue
FROM monthly
ORDER BY order_year, order_month;


-- A5. Pareto Analysis — Cumulative Revenue by Customer
WITH customer_rev AS (
    SELECT
        c.customer_name,
        SUM(f.sales) AS total_sales
    FROM fact_orders f
    JOIN dim_customers c
        ON f.customer_id = c.customer_id
    GROUP BY c.customer_name
)
SELECT
    customer_name,
    ROUND(total_sales, 2) AS total_sales,

    ROUND(
        SUM(total_sales) OVER (
            ORDER BY total_sales DESC
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ),
        2
    ) AS running_revenue,

    ROUND(
        SUM(total_sales) OVER (
            ORDER BY total_sales DESC
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) * 100.0
        / NULLIF(SUM(total_sales) OVER (), 0),
        2
    ) AS cumulative_pct_of_revenue

FROM customer_rev
ORDER BY total_sales DESC;


-- A6. Top 20% of Customers by Revenue
WITH customer_rev AS (
    SELECT
        c.customer_name,
        SUM(f.sales) AS total_sales
    FROM fact_orders f
    JOIN dim_customers c
        ON f.customer_id = c.customer_id
    GROUP BY c.customer_name
),
ranked AS (
    SELECT
        customer_name,
        total_sales,
        NTILE(5) OVER (
            ORDER BY total_sales DESC
        ) AS quintile
    FROM customer_rev
)
SELECT
    customer_name,
    ROUND(total_sales, 2) AS total_sales
FROM ranked
WHERE quintile = 1
ORDER BY total_sales DESC;


-- A7. Revenue Share Generated by Top 20% Customers
WITH customer_rev AS (
    SELECT
        c.customer_name,
        SUM(f.sales) AS total_sales
    FROM fact_orders f
    JOIN dim_customers c
        ON f.customer_id = c.customer_id
    GROUP BY c.customer_name
),
ranked AS (
    SELECT
        customer_name,
        total_sales,
        NTILE(5) OVER (
            ORDER BY total_sales DESC
        ) AS quintile
    FROM customer_rev
)
SELECT
    ROUND(
        SUM(
            CASE
                WHEN quintile = 1 THEN total_sales
                ELSE 0
            END
        ),
        2
    ) AS top20pct_revenue,

    ROUND(SUM(total_sales), 2) AS total_revenue,

    ROUND(
        SUM(
            CASE
                WHEN quintile = 1 THEN total_sales
                ELSE 0
            END
        ) * 100.0
        / NULLIF(SUM(total_sales), 0),
        2
    ) AS top20pct_share

FROM ranked;


-- A8. VIEW — Repeat Customers
DROP VIEW IF EXISTS vw_repeat_customers;

CREATE VIEW vw_repeat_customers AS
SELECT
    c.customer_name,
    COUNT(DISTINCT f.order_id) AS order_count,
    ROUND(SUM(f.sales), 2) AS total_sales,
    ROUND(SUM(f.profit), 2) AS total_profit
FROM fact_orders f
JOIN dim_customers c
    ON f.customer_id = c.customer_id
GROUP BY c.customer_name
HAVING COUNT(DISTINCT f.order_id) > 1;


-- Validate repeat-customer view
SELECT
    COUNT(*) AS repeat_customer_count
FROM vw_repeat_customers;


-- A9. Quarterly Growth Rate
WITH quarterly AS (
    SELECT
        order_year,
        order_quarter,
        SUM(sales) AS quarterly_sales
    FROM fact_orders
    GROUP BY order_year, order_quarter
),
quarterly_growth AS (
    SELECT
        order_year,
        order_quarter,
        quarterly_sales,
        LAG(quarterly_sales) OVER (
            ORDER BY order_year, order_quarter
        ) AS previous_quarter_sales
    FROM quarterly
)
SELECT
    order_year,
    order_quarter,
    ROUND(quarterly_sales, 2) AS quarterly_sales,

    ROUND(
        (
            quarterly_sales - previous_quarter_sales
        ) * 100.0
        / NULLIF(previous_quarter_sales, 0),
        2
    ) AS qoq_growth_pct

FROM quarterly_growth
ORDER BY order_year, order_quarter;


-- A10. Profit Margin by Customer Segment
-- Includes a DENSE_RANK leaderboard.
SELECT
    c.segment,
    ROUND(SUM(f.sales), 2) AS total_sales,
    ROUND(SUM(f.profit), 2) AS total_profit,

    ROUND(
        SUM(f.profit) * 100.0
        / NULLIF(SUM(f.sales), 0),
        2
    ) AS margin_pct,

    DENSE_RANK() OVER (
        ORDER BY
            SUM(f.profit) * 100.0
            / NULLIF(SUM(f.sales), 0) DESC
    ) AS margin_rank

FROM fact_orders f
JOIN dim_customers c
    ON f.customer_id = c.customer_id
GROUP BY c.segment
ORDER BY margin_rank;